dist: trusty
language: cpp
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install qttools5-dev qtbase5-dev-tools qtbase5-dev qtdeclarative5-dev qtscript5-dev libqt5core5a libqt5gui5 libqt5network5 libqt5qml5 libqt5quick5 libqt5script5 libqt5sql5 libqt5webkit5 libqt5widgets5 libqt5x11extras5 libqt5xml5libqt5sql5-sqlite libgadu3 libgadu-dev cmake
before_script:
  - git clone https://github.com/vogel/injeqt.git
  - cd injeqt
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr ..
  - make
  - make test
  - sudo make install
  - cd ..
  - cd ..
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make
  - make test
