dist: trusty
language: cpp
before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty
  - sudo apt-get update -qq
  - sudo apt-get install -y qt55[QTPACKAGE] libgadu3 libgadu-dev cmake
before_script:
  - source /opt/qt55/bin/qt55-env.sh
  - git clone https://github.com/vogel/injeqt.git
  - cd injeqt
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr ..
  - make
  - make test
  - sudo make install
  - cd ..
  - cd ..
script:
  - source /opt/qt55/bin/qt55-env.sh
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make
  - make test
